version: '3.8'

services:
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var_back:/var/www/symfony/var
            - symfony_app_vendor_back:/var/www/symfony/vendor
        networks:
            - symfony_app

    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var_back:/var/www/symfony/var
            - symfony_app_vendor_back:/var/www/symfony/vendor
        ports:
            - 8082:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx.local

volumes:
    symfony_app_var_back:
    symfony_app_vendor_back:
    db_app:
    mailpit_data:

networks:
    symfony_app:
        external: true
