name: Run PHPUnit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          cd back/.docker/php
          docker build -t my-php-app --build-arg TIMEZONE=Europe/Paris -f Dockerfile .

      - name: Install PHP dependencies
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}/back:/var/www/symfony -w /var/www/symfony my-php-app sh -c "composer install"

      - name: Run PHPUnit tests
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}/back:/var/www/symfony -w /var/www/symfony my-php-app sh -c "php bin/phpunit"
